/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox1:597094:
  println("checkbox1 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox1:597094:

public void checkbox2_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox2:721138:
  println("checkbox2 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox2:721138:

public void checkbox3_clicked1(GCheckbox source, GEvent event) { //_CODE_:checkbox3:703054:
  println("checkbox3 - GCheckbox >> GEvent." + event + " @ " + millis());
} //_CODE_:checkbox3:703054:

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:textfield1:346810:
  println("textfield1 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield1:346810:

public void textfield2_change1(GTextField source, GEvent event) { //_CODE_:textfield2:845781:
  println("textfield2 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield2:845781:

public void textfield4_change1(GTextField source, GEvent event) { //_CODE_:textfield4:685792:
  println("textfield4 - GTextField >> GEvent." + event + " @ " + millis());
} //_CODE_:textfield4:685792:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  togGroup1 = new GToggleGroup();
  togGroup2 = new GToggleGroup();
  checkbox1 = new GCheckbox(this, 30, 10, 120, 20);
  checkbox1.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox1.setText("moonGravity");
  checkbox1.setLocalColorScheme(GCScheme.RED_SCHEME);
  checkbox1.setOpaque(false);
  checkbox1.addEventHandler(this, "checkbox1_clicked1");
  checkbox2 = new GCheckbox(this, 30, 30, 120, 20);
  checkbox2.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox2.setText("Color");
  checkbox2.setLocalColorScheme(GCScheme.RED_SCHEME);
  checkbox2.setOpaque(false);
  checkbox2.addEventHandler(this, "checkbox2_clicked1");
  checkbox3 = new GCheckbox(this, 30, 50, 120, 20);
  checkbox3.setIconAlign(GAlign.LEFT, GAlign.MIDDLE);
  checkbox3.setText("removeSat");
  checkbox3.setLocalColorScheme(GCScheme.RED_SCHEME);
  checkbox3.setOpaque(false);
  checkbox3.addEventHandler(this, "checkbox3_clicked1");
  label1 = new GLabel(this, 170, 10, 80, 20);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("PlanetG");
  label1.setLocalColorScheme(GCScheme.RED_SCHEME);
  label1.setOpaque(false);
  textfield1 = new GTextField(this, 170, 30, 80, 20, G4P.SCROLLBARS_NONE);
  textfield1.setText("9.82");
  textfield1.setOpaque(true);
  textfield1.addEventHandler(this, "textfield1_change1");
  label2 = new GLabel(this, 250, 10, 80, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("MoonG");
  label2.setLocalColorScheme(GCScheme.RED_SCHEME);
  label2.setOpaque(false);
  textfield2 = new GTextField(this, 250, 30, 80, 20, G4P.SCROLLBARS_NONE);
  textfield2.setText("1.62");
  textfield2.setOpaque(true);
  textfield2.addEventHandler(this, "textfield2_change1");
  label4 = new GLabel(this, 170, 70, 80, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("Time");
  label4.setLocalColorScheme(GCScheme.RED_SCHEME);
  label4.setOpaque(false);
  textfield4 = new GTextField(this, 170, 90, 80, 20, G4P.SCROLLBARS_NONE);
  textfield4.setText("20");
  textfield4.setOpaque(true);
  textfield4.addEventHandler(this, "textfield4_change1");
}

// Variable declarations 
// autogenerated do not edit
GToggleGroup togGroup1; 
GToggleGroup togGroup2; 
GCheckbox checkbox1; 
GCheckbox checkbox2; 
GCheckbox checkbox3; 
GLabel label1; 
GTextField textfield1; 
GLabel label2; 
GTextField textfield2; 
GLabel label4; 
GTextField textfield4; 
